packages:
  - cri-o-2:1.17.0-1.module_f31+7715+4eeda4d1.x86_64
#  - kubelet-1.17.3-0
#  - kubeadm-1.17.3-0
#  - kubectl-1.17.3-0


#https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
postprocess:
  - |
    #!/usr/bin/env bash
    sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

  - |
    #!/usr/bin/env bash
    cat <<EOF >  /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    EOF